
[colors]
primary = { background = "#000e1c" }

[window]
padding = { x = 5, y = 0 }
dynamic_padding = true
opacity = 0.9


[font]
size = 9.5
normal = { family = "MesloLGM Nerd Font" }

[keyboard]
bindings = [
{ key = "F11",  action = "ToggleFullScreen" },
# { key = "c", mods = "Control|Shift",  action = "CopySelection" },
]

[terminal]

[general]
import = [
    "~/.config/alacritty/alacritty-theme/themes/nord.toml"
]
# osc52 = "CopyPaste"
