import = [
#    "~/.config/alacritty/themes/themes/github_light.toml"
#    "~/.config/alacritty/themes/themes/gruvbox_light.toml"
    "~/.config/alacritty/themes/themes/night_owlish_light.toml"
]


[window]
padding = { x = 15, y = 10 }
dynamic_padding = true
opacity = 0.9
# decorations = "None"

[font]
size = 13
normal = { family = "MesloLGM NerdFont" }

[keyboard]
bindings = [
{ key = "F11",  action = "ToggleFullScreen" },
# { key = "c", mods = "Control|Shift",  action = "CopySelection" },
]

[terminal]
# osc52 = "CopyPaste"




